# Generated by Django 4.0.2 on 2022-02-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifier',
            name='content',
        ),
        migrations.AddField(
            model_name='classifier',
            name='recognizer',
            field=models.FileField(default=1, upload_to='recognizers/'),
            preserve_default=False,
        ),
    ]
